# Generated by Django 5.2.5 on 2025-09-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhousecontrol',
            name='desired_temperature',
        ),
        migrations.AddField(
            model_name='greenhousecontrol',
            name='max_temperature',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='greenhousecontrol',
            name='min_temperature',
            field=models.FloatField(default=22.0),
        ),
    ]
