# Generated by Django 5.2.5 on 2025-10-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0002_remove_greenhousecontrol_desired_temperature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='greenhousecontrol',
            name='singleton',
        ),
    ]
