# Generated by Django 5.2.5 on 2025-10-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0003_hourlyaverage_remove_greenhousecontrol_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousecontrol',
            name='singleton',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='hourlyaverage',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hourlyaverage',
            name='timestamp',
            field=models.DateTimeField(unique=True),
        ),
    ]
