# Generated by Django 5.2.5 on 2025-10-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0004_greenhousecontrol_singleton_hourlyaverage_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousecontrol',
            name='automatic_mode',
            field=models.BooleanField(default=True),
        ),
    ]
