# Generated by Django 5.2.5 on 2025-11-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0006_curtainlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousecontrol',
            name='curtain_status',
            field=models.CharField(default='stop', max_length=10),
        ),
        migrations.AlterField(
            model_name='curtainlog',
            name='action',
            field=models.CharField(choices=[('open', 'Aberta'), ('stop', 'Parada'), ('close', 'Fechada')], max_length=10),
        ),
    ]
