# Generated by Django 5.2.5 on 2025-11-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0007_greenhousecontrol_curtain_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousecontrol',
            name='last_esp_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
