# Generated by Django 5.2.5 on 2025-11-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0008_greenhousecontrol_last_esp_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtainlog',
            name='side',
            field=models.CharField(choices=[('left', 'Esquerda'), ('right', 'Direita'), ('both', 'Ambas')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='greenhousecontrol',
            name='auto_left_action',
            field=models.CharField(choices=[('open', 'Abrir'), ('close', 'Fechar'), ('stop', 'Parar')], default='stop', max_length=10),
        ),
        migrations.AddField(
            model_name='greenhousecontrol',
            name='auto_right_action',
            field=models.CharField(choices=[('open', 'Abrir'), ('close', 'Fechar'), ('stop', 'Parar')], default='stop', max_length=10),
        ),
        migrations.AddField(
            model_name='greenhousecontrol',
            name='left_is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='greenhousecontrol',
            name='manual_left_action',
            field=models.CharField(choices=[('open', 'Abrir'), ('close', 'Fechar'), ('stop', 'Parar')], default='stop', max_length=10),
        ),
        migrations.AddField(
            model_name='greenhousecontrol',
            name='manual_right_action',
            field=models.CharField(choices=[('open', 'Abrir'), ('close', 'Fechar'), ('stop', 'Parar')], default='stop', max_length=10),
        ),
        migrations.AddField(
            model_name='greenhousecontrol',
            name='right_is_open',
            field=models.BooleanField(default=False),
        ),
    ]
