# Generated by Django 5.2.5 on 2025-11-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0009_curtainlog_side_greenhousecontrol_auto_left_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousecontrol',
            name='esp_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curtainlog',
            name='side',
            field=models.CharField(choices=[('left', 'Esquerda'), ('right', 'Direita'), ('both', 'Ambas')], default='both', max_length=6),
        ),
        migrations.AlterField(
            model_name='greenhousecontrol',
            name='auto_left_action',
            field=models.CharField(default='stop', max_length=10),
        ),
        migrations.AlterField(
            model_name='greenhousecontrol',
            name='auto_right_action',
            field=models.CharField(default='stop', max_length=10),
        ),
        migrations.AlterField(
            model_name='greenhousecontrol',
            name='manual_left_action',
            field=models.CharField(default='stop', max_length=10),
        ),
        migrations.AlterField(
            model_name='greenhousecontrol',
            name='manual_right_action',
            field=models.CharField(default='stop', max_length=10),
        ),
    ]
