# Generated by Django 5.2.5 on 2025-11-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0010_greenhousecontrol_esp_ip_alter_curtainlog_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousecontrol',
            name='curtain_move_time_seconds',
            field=models.PositiveIntegerField(default=120, help_text='Tempo em segundos para a cortina abrir/fechar totalmente.'),
        ),
    ]
